[package]
name = "trane-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
trane = "0.12.0"

[dev-dependencies]
fs_extra = "1.3.0"
tempfile = "3.4.0"
